
name: Request Transfer

on:
  schedule:
    - cron:  '0 0 1/2 * *'

jobs:
  build:
    name: Request Transfer
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl \
            -X POST \
            -H 'Accept: application/vnd.github+json' \
            -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'\
            -H 'X-GitHub-Api-Version: 2022-11-28' \
            https://api.github.com/repos/cloudsftp/clouds666/transfer \
            -d '{"new_owner":"clouds666"}'
