
name: Request Transfer

on:
  schedule:
    - cron:  '20 16 2/2 * *'
  push:
    branches:
      - main

jobs:
  build:
    name: Request Transfer
    runs-on: ubuntu-latest
    steps:
      - name: Check if user still exists
        run: |
          curl -s -o /dev/null -w "%{http_code}" \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/users/clouds666 > status_code
          if [ "$(cat status_code)" = 404 ]; then echo user does not exist; exit 1; fi

      - name: Request repo transfer if user exists
        run: |
          curl \
            -X POST \
            -H 'Accept: application/vnd.github+json' \
            -H 'Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}'\
            -H 'X-GitHub-Api-Version: 2022-11-28' \
            https://api.github.com/repos/cloudsftp/clouds666/transfer \
            -d '{"new_owner":"clouds666"}'
